### PR TITLE
Update job.rb

### PR DESCRIPTION
**Pull request by andyfenna**
added job state property to the job class

### CODE REVIEW

**Comment by andyfenna** [comment]
addedd job state property to the job class

**Comment by i11** [comment]
Hi,

Thanks! Could you please squash 3 PR into one? It seems unnecessary to have them as separate PRs.

**Comment by andyfenna** [comment]
Yeah sure, I've closed the previous 2. how do i add changed now to the parse_job.rb?

**Comment by i11** [comment]
Great! Just push commit to the same branch and the PR will get updated.

**Comment by andyfenna** [comment]
I cloned the code locally and changed it but I was unable to push to remote. therefore i modified the files online, this created multiple PRs.

**Comment by i11** [comment]
You need to fork the project before making any changes and creating PRs. Please consult https://help.github.com/articles/using-pull-requests/

**Pull request closed without merging**
